name: DevSecOps Security Scan

on: [push, pull_request]

jobs:
  security:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1) Make sure Python is set up (and pinned) so you have a consistent environment.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run Semgrep (Static Code Analysis)
        run: |
          pip install semgrep
          semgrep scan --config=auto

      - name: Run Trivy (Dependency Scan)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
          ./bin/trivy fs .

      - name: Run Checkov (Terraform Security Scan)
        run: |
          mkdir -p infra
          pip install 'packaging>=23.0,<24.0' 'jmespath>=1.0.0,<2.0.0'
          pip install checkov==3.2.377
          checkov -d infra/

      - name: Run Prowler (AWS Security Audit)
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          rm -rf prowler-repo
          git clone https://github.com/prowler-cloud/prowler.git prowler-repo
          cd prowler-repo
          echo "=== Debug: Prowler Repo Contents ==="
          ls -al
          pip install poetry
          poetry install
          poetry run python prowler.py -M json-ocsf -o prowler-report.json

      - name: Run ScoutSuite (AWS Security Report)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Create and activate a dedicated virtual environment
          python -m venv venv
          source venv/bin/activate

          # Upgrade pip (recommended)
          pip install --upgrade pip

          # Install ScoutSuite
          pip install scoutsuite

          # Verify scoutsuite is installed and in PATH
          which scoutsuite
          scoutsuite --version

          # Run ScoutSuite
          scoutsuite -p aws --report scoutsuite-report

      - name: Upload Security Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            prowler-repo/prowler-report.json
            scoutsuite-report
