name: Debug ScoutSuite

on: [push]

jobs:
  scoutsuite-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Debug ScoutSuite in venv
        run: |
          set -euxo pipefail

          echo "=== System Python info ==="
          python --version
          which python

          echo "=== Create venv ==="
          python -m venv venv

          echo "=== Check venv/bin ==="
          ls -al venv/bin

          echo "=== Activate venv ==="
          source venv/bin/activate

          echo "=== Python in venv ==="
          which python
          python --version

          echo "=== Upgrade pip ==="
          python -m pip install --upgrade pip

          echo "=== Install ScoutSuite ==="
          python -m pip install scoutsuite

          echo "=== Check installed packages ==="
          python -m pip list | grep -i scout || true
          python -m pip show scoutsuite || true

          echo "=== Attempting to run ScoutSuite ==="
          python -m scoutsuite --version
          python -m scoutsuite --help
