name: DevSecOps Security Scan

on: [push, pull_request]

jobs:
  security:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep (Static Code Analysis)
        run: |
          pip install semgrep
          semgrep scan --config=auto

      - name: Run Trivy (Dependency Scan)
        run: |
          # Install Trivy into ./bin
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
          # Call Trivy explicitly from ./bin
          ./bin/trivy fs .

      - name: Run Checkov (Terraform Security Scan)
        run: |
          # Ensure infra folder exists so Checkov doesn't complain
          mkdir -p infra
          pip install checkov
          checkov -d infra/

      - name: Run Prowler (AWS Security Audit)
        continue-on-error: true  # Continue if failing checks (exit code 3) occur
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Remove any leftover folder
          rm -rf prowler-repo
          # Clone fresh
          git clone https://github.com/prowler-cloud/prowler.git prowler-repo
          cd prowler-repo

          echo "=== Debug: Prowler Repo Contents ==="
          ls -al

          # Install Poetry
          pip install poetry

          # Install all dependencies
          poetry install

          # Run prowler with Poetry (json-ocsf output)
          poetry run python prowler.py -M json-ocsf -o prowler-report.json

      - name: Run ScoutSuite (AWS Security Report)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # METHOD 3: Use a virtual environment for ScoutSuite
          python -m venv venv
          source venv/bin/activate

          # Install ScoutSuite into the venv
          pip install scoutsuite

          # Now the 'scoutsuite' command is available in this venv
          scoutsuite -p aws --report scoutsuite-report

      - name: Upload Security Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            prowler-repo/prowler-report.json
            scoutsuite-report
