name: DevSecOps Security Scan

on: [push, pull_request]

jobs:
  security:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep (Static Code Analysis)
        run: |
          pip install semgrep
          semgrep scan --config=auto

      - name: Run Trivy (Dependency Scan)
        run: |
          # Install Trivy into ./bin
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin
          # Call Trivy explicitly from ./bin
          ./bin/trivy fs .

      - name: Run Checkov (Terraform Security Scan)
        run: |
          pip install checkov
          checkov -d infra/

      - name: Run Prowler (AWS Security Audit)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Remove any leftover folder from previous runs
          rm -rf prowler-repo
          # Clone the Prowler repo into "prowler-repo" (avoid naming it "prowler")
          git clone https://github.com/prowler-cloud/prowler.git prowler-repo
          cd prowler-repo
          # Make the prowler script executable
          chmod +x prowler
          # Run the prowler script
          ./prowler -M json -o prowler-report.json

      - name: Run ScoutSuite (AWS Security Report)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install scoutsuite
          scoutsuite -p aws --report scoutsuite-report

      - name: Upload Security Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            prowler-repo/prowler-report.json
            scoutsuite-report
